version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nutrition-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - ollama
    networks:
      - nutrition-network
    restart: on-failure

  db:
    image: postgres:14
    container_name: nutrition-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - nutrition-network
    restart: on-failure

  ollama:
    build:
      context: ./ollama
      dockerfile: Dockerfile
    container_name: nutrition-ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - nutrition-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: on-failure

networks:
  nutrition-network:
    driver: bridge

volumes:
  postgres_data:
  ollama_data: 